[versions]
activity = "1.9.2"
agp = "8.7.0"
alwan = "1.0.1"
androidx-animation = "1.0.0"
androidx-core = "1.13.1"
biometric = "1.2.0-alpha05"
coil = "2.7.0"
compose-bom = "2024.09.03"
compose-accompanist = "0.36.0"
coroutines = "1.9.0"
constraint-layout = "2.1.4"
coordinator-layout = "1.2.0"
datastore = "1.1.1"
dynamic-animation = "1.1.0-alpha03"
fuzzywuzzy = "1.4.0"
hoko-blur = "1.5.3"
immutables = "0.3.8"
kotlin = "2.0.20"
koin = "3.5.6"
koin-ksp = "1.3.1"
ksp = "2.0.20-1.0.25"
lifecycle = "2.8.6"
lifecycle-ext = "2.2.0"
material = "1.12.0"
material-kolor = "2.0.0"
navigation = "2.8.2"
okhttp = "5.0.0-alpha.14"
owm = "2.1.0"
palette = "1.0.0"
persian-date = "1.7.1"
preference = "1.2.1"
protobuf-plugin = "0.9.4"
protobuf-lib = "3.25.3"
recycler-view = "1.3.2"
reorderable = "2.3.3"
restriction-bypass = "2.2"
room = "2.6.1"
serialization = "1.7.3"
simple-storage = "2.0.0"
slice = "1.1.0-alpha02"

junit = "4.13.2"
junit5 = "5.11.1"
truth = "1.4.4"
mockito = "5.14.1"
dexmaker = "1.2"
androidx-annotation = "1.8.2"
androidx-test = "1.2.1"
androidx-runner = "1.6.2"
androidx-rules = "1.6.1"
uiautomator = "2.3.0"
support-runner = "1.0.2"
support-rules = "1.0.2"
support-uiautomator = "2.1.3"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutables" }

androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-animation = { group = "androidx.core", name = "core-animation", version.ref = "androidx-animation" }
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout" }
androidx-coordinator-layout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinator-layout" }
androidx-dynamic-animation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "dynamic-animation" }
androidx-palette = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recycler-view" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }

material = { module = "com.google.android.material:material", version.ref = "material" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
slice = { module = "androidx.slice:slice-core", version.ref = "slice" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-lib" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
owm = { module = "com.github.KwabenBerko:OpenWeatherMap-Android-Library", version.ref = "owm" }
simple-storage = { module = "com.anggrayudi:storage", version.ref = "simple-storage" }
restriction-bypass = { module = "com.github.ChickenHook:RestrictionBypass", version.ref = "restriction-bypass" }
persian-date = { module = "com.github.samanzamani:PersianDate", version.ref = "persian-date" }
alwan = { module = "com.raedapps:alwan", version.ref = "alwan" }
hoko-blur = { module = "io.github.hokofly:hoko-blur", version.ref = "hoko-blur" }
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-ext" }

coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "compose-accompanist" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }

junit = { module = "junit:junit", version.ref = "junit" }
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
dexmaker-lib = { module = "com.google.dexmaker:dexmaker", version.ref = "dexmaker" }
dexmaker-mockito = { module = "com.google.dexmaker:dexmaker-mockito", version.ref = "dexmaker" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
support-runner = { module = "com.android.support.test:runner", version.ref = "support-runner" }
support-rules = { module = "com.android.support.test:rules", version.ref = "support-rules" }
support-uiautomator = { module = "com.android.support.test.uiautomator:uiautomator-v18", version.ref = "support-uiautomator" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }