[versions]
activity = "1.12.2"
agp = "9.0.0"
alwan = "1.0.1"
coil = "2.7.0"
compose-accompanist = "0.37.3"
compose-bom = "2026.01.00"
core-animation = "1.0.0"
core-ktx= "1.17.0"
coroutines = "1.10.2"
constraint-layout = "2.2.1"
coordinator-layout = "1.3.0"
dagger = "2.59"
datastore = "1.2.0"
dynamic-animation = "1.1.0"
fuzzywuzzy = "1.4.0"
error-prone-annotations = "2.46.0"
graphics-shapes = "1.1.0"
guava = "33.5.0-android"
hoko-blur = "1.5.3"
immutables = "0.4.0"
inject = "1"
jakarta-inject = "2.0.1"
kotlin = "2.3.0"
koin = "4.1.1"
koin-ksp = "2.3.1"
kotlin-stdlib-jdk7 = "2.2.21"
lifecycle = "2.10.0"
lifecycle-ext = "2.2.0"
material = "1.13.0"
material-icons = "1.7.8"
material-kolor = "4.1.0"

navigation = "2.9.6"
okhttp = "5.3.2"
owm = "2.1.0"
palette = "1.0.0"
preference = "1.2.1"
protobuf-plugin = "0.9.6"
protobuf-lib = "4.33.4"
recycler-view = "1.4.0"
reorderable = "3.0.0"
restriction-bypass = "2.2"
room = "2.8.4"
serialization = "1.10.0"
slice = "1.1.0-alpha02"
window = "1.6.0-alpha01"

junit = "4.13.2"
junit5 = "6.0.2"
truth = "1.4.5"
mockito = "5.21.0"
dexmaker = "1.2"
androidx-annotation = "1.9.1"
androidx-test = "1.3.0"
androidx-runner = "1.7.0"
androidx-rules = "1.7.0"
uiautomator = "2.3.0"
support-runner = "1.0.2"
support-rules = "1.0.2"
support-uiautomator = "2.1.3"
material3 = "1.4.0"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "compose-accompanist" }
alwan = { module = "com.raedapps:alwan", version.ref = "alwan" }
annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutables" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout" }
compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-window = { module = "androidx.compose.material3:material3-window-size-class" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core-android", version.ref = "material-icons" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout" }
coordinator-layout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinator-layout" }
core-animation = {group = "androidx.core", name="core-animation", version.ref="core-animation"}
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
dynamic-animation = { group = "androidx.dynamicanimation", name = "dynamicanimation", version.ref = "dynamic-animation" }
error-prone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error-prone-annotations" }
fuzzywuzzy = { module = "me.xdrop:fuzzywuzzy", version.ref = "fuzzywuzzy" }
graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphics-shapes" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
jakarta-inject = { group = "jakarta.inject", name = "jakarta.inject-api", version.ref = "jakarta-inject" }
java-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin-stdlib-jdk7" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-ext" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
owm = { module = "com.github.KwabenBerko:OpenWeatherMap-Android-Library", version.ref = "owm" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf-lib" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recycler-view" }
#restriction-bypass = { module = "com.github.ChickenHook:RestrictionBypass", version.ref = "restriction-bypass" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
slice-core = { group = "androidx.slice", name = "slice-core", version.ref = "slice" }
window = { module = "androidx.window:window", version.ref = "window" }

compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
dexmaker-lib = { module = "com.google.dexmaker:dexmaker", version.ref = "dexmaker" }
dexmaker-mockito = { module = "com.google.dexmaker:dexmaker-mockito", version.ref = "dexmaker" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
runner = { module = "com.android.support.test:runner", version.ref = "support-runner" }
rules = { module = "com.android.support.test:rules", version.ref = "support-rules" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
test-rules = { module = "androidx.test:rules", version.ref = "androidx-rules" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-runner" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
uiautomator-v18 = { module = "com.android.support.test.uiautomator:uiautomator-v18", version.ref = "support-uiautomator" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
google-ksp = "com.google.devtools.ksp:2.3.4"
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }